package com.danielgarcia.expensector.database

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        db.execSQL("CREATE TABLE IF NOT EXISTS `financial_spaces` (`id` TEXT NOT NULL, `code` TEXT, `displayName` TEXT NOT NULL, `description` TEXT, `defaultCurrencyCode` TEXT NOT NULL, `isDefault` INTEGER NOT NULL, `active` INTEGER NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, `archivedAtEpochMillis` INTEGER, PRIMARY KEY(`id`))")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_financial_spaces_code` ON `financial_spaces` (`code`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_financial_spaces_isDefault` ON `financial_spaces` (`isDefault`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `budget_period_configurations` (`id` TEXT NOT NULL, `financialSpaceId` TEXT NOT NULL, `periodType` TEXT NOT NULL, `effectiveFrom` TEXT NOT NULL, `effectiveTo` TEXT, `weekendAdjustmentStrategy` TEXT NOT NULL, `active` INTEGER NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`financialSpaceId`) REFERENCES `financial_spaces`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_budget_period_configurations_financialSpaceId` ON `budget_period_configurations` (`financialSpaceId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_budget_period_configurations_active` ON `budget_period_configurations` (`active`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `budget_periods` (`id` TEXT NOT NULL, `financialSpaceId` TEXT NOT NULL, `configurationId` TEXT NOT NULL, `periodKey` TEXT NOT NULL, `periodType` TEXT NOT NULL, `startDate` TEXT NOT NULL, `endDate` TEXT NOT NULL, `nominalExpectedPaymentDate` TEXT NOT NULL, `adjustedExpectedPaymentDate` TEXT NOT NULL, `actualPaymentDate` TEXT, `status` TEXT NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`financialSpaceId`) REFERENCES `financial_spaces`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT, FOREIGN KEY(`configurationId`) REFERENCES `budget_period_configurations`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_budget_periods_financialSpaceId` ON `budget_periods` (`financialSpaceId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_budget_periods_configurationId` ON `budget_periods` (`configurationId`)")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_budget_periods_configurationId_periodKey` ON `budget_periods` (`configurationId`, `periodKey`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `financial_accounts` (`id` TEXT NOT NULL, `financialSpaceId` TEXT NOT NULL, `accountType` TEXT NOT NULL, `displayName` TEXT NOT NULL, `normalizedName` TEXT NOT NULL, `institutionName` TEXT, `normalizedInstitutionName` TEXT, `alias` TEXT, `currencyCode` TEXT NOT NULL, `lastFourDigits` TEXT, `displayOrder` INTEGER NOT NULL, `active` INTEGER NOT NULL, `includeInAvailableCash` INTEGER NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, `archivedAtEpochMillis` INTEGER, PRIMARY KEY(`id`), FOREIGN KEY(`financialSpaceId`) REFERENCES `financial_spaces`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_financial_accounts_financialSpaceId` ON `financial_accounts` (`financialSpaceId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_financial_accounts_accountType` ON `financial_accounts` (`accountType`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `credit_card_details` (`financialAccountId` TEXT NOT NULL, `issuer` TEXT NOT NULL, `productName` TEXT, `creditLimitMinor` INTEGER, `currencyCode` TEXT NOT NULL, `statementClosingDay` INTEGER NOT NULL, `paymentDueDay` INTEGER NOT NULL, `annualInterestRateBasisPoints` INTEGER, `active` INTEGER NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`financialAccountId`), FOREIGN KEY(`financialAccountId`) REFERENCES `financial_accounts`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `opening_balances` (`id` TEXT NOT NULL, `financialAccountId` TEXT NOT NULL, `financialSpaceId` TEXT NOT NULL, `amountMinor` INTEGER NOT NULL, `currencyCode` TEXT NOT NULL, `effectiveDate` TEXT NOT NULL, `type` TEXT NOT NULL, `note` TEXT, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`financialAccountId`) REFERENCES `financial_accounts`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT, FOREIGN KEY(`financialSpaceId`) REFERENCES `financial_spaces`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_opening_balances_financialAccountId` ON `opening_balances` (`financialAccountId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_opening_balances_financialSpaceId` ON `opening_balances` (`financialSpaceId`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `categories` (`id` TEXT NOT NULL, `financialSpaceId` TEXT NOT NULL, `purpose` TEXT NOT NULL, `displayName` TEXT NOT NULL, `normalizedName` TEXT NOT NULL, `description` TEXT, `parentCategoryId` TEXT, `hierarchyLevel` INTEGER NOT NULL, `displayOrder` INTEGER NOT NULL, `active` INTEGER NOT NULL, `systemProvided` INTEGER NOT NULL, `mergedIntoCategoryId` TEXT, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, `archivedAtEpochMillis` INTEGER, PRIMARY KEY(`id`), FOREIGN KEY(`financialSpaceId`) REFERENCES `financial_spaces`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT, FOREIGN KEY(`parentCategoryId`) REFERENCES `categories`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_categories_financialSpaceId` ON `categories` (`financialSpaceId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_categories_parentCategoryId` ON `categories` (`parentCategoryId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_categories_purpose` ON `categories` (`purpose`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_categories_normalizedName` ON `categories` (`normalizedName`)")
        db.execSQL("CREATE TABLE IF NOT EXISTS `category_merge_records` (`id` TEXT NOT NULL, `financialSpaceId` TEXT NOT NULL, `sourceCategoryId` TEXT NOT NULL, `destinationCategoryId` TEXT NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`financialSpaceId`) REFERENCES `financial_spaces`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT, FOREIGN KEY(`sourceCategoryId`) REFERENCES `categories`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT, FOREIGN KEY(`destinationCategoryId`) REFERENCES `categories`(`id`) ON UPDATE NO ACTION ON DELETE RESTRICT)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_category_merge_records_sourceCategoryId` ON `category_merge_records` (`sourceCategoryId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_category_merge_records_financialSpaceId` ON `category_merge_records` (`financialSpaceId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_category_merge_records_destinationCategoryId` ON `category_merge_records` (`destinationCategoryId`)")
    }
}
